### ISSUE TITLE
Colega, ¿dónde está mi imagen?

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-rqlromo#1]
Cuidado enlazando imagenes de otros dominios, si mañana la web de Adalab la mueve de localización, nuestra imagen fallará.

Mejor si la descargamos, la guardamos en una carpetica `images` en nuestro proyecto, y la enlazamos relativamente!

**Comment by rqlromo** [comment]
Hecho!

**Comment by rqlromo** [comment]
Hecho!
