### ISSUE TITLE
Arreglar semántica

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-rqlromo#3]
Hay algunos errores faciles de solucionar:

- Falta contenido en `<title>`
- Necesitamos un H1 y el titulo principal del contenido de la página `Creando Diversidad Digital`
- El mensaje alternativo de la imagen esta raruno, mejor algo que la describa, que un mensaje de error (si la imagen no carga el error estará implicito ;)
- El logo estaría mejor fuera de la navegacion principal

A darle caña!

**Comment by rqlromo** [comment]
Hecho!
