### ISSUE TITLE
Acabar la web

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-rqlromo#5]
Cuando acabes el resto de issues, ¿te animas?

Hay que:

- Alinear los items del menú (inline-block o flex... ;)
- Hacer que el body o etiqueta madre de header y main ocupe todo el alto (vh mola).
- Hacer que main ocupe todo el alto libre que deja header (igual si son items flex la cosa se apaña)
- Centrar el título
- En la version tablet recolocar logo y menú

![](https://media.giphy.com/media/EI4svF454qiTm/giphy.gif)

**Comment by nasivuela** [comment]
Buen trabajo @rqlromo !!

Dale caña que se han quedado unos bordes rojos por ahí y falta la tablet! A por ello.

**Comment by rqlromo** [comment]
Fuera bordes rojos y dentro mediaqueries! XD 
Que paciencia tienes nasi ;-)

**Comment by nasivuela** [comment]
Ole, buen trabajo @rqlromo !

![](https://media.giphy.com/media/8g63zqQ5RPt60/giphy.gif)
